"""
PDF Report Generator for UnitSim Analysis
=========================================

Creates professional PDF reports with charts, tables, and analysis summaries
using ReportLab for comprehensive business analysis documentation.
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.linecharts import HorizontalLineChart
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics.charts.piecharts import Pie
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from typing import Dict, Any, List, Optional
from datetime import datetime
import io
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend


def generate_pdf_report(
    analysis_type: str,
    input_params: Dict[str, Any],
    results: Dict[str, Any],
    title: Optional[str] = None,
    description: Optional[str] = None,
    include_charts: bool = True
) -> bytes:
    """
    Generate comprehensive PDF report for analysis
    
    Args:
        analysis_type: Type of analysis
        input_params: Input parameters
        results: Analysis results
        title: Optional custom title
        description: Optional description
        include_charts: Whether to include visualizations
    
    Returns:
        PDF as bytes
    """
    
    # Create PDF buffer
    buffer = io.BytesIO()
    
    # Create document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=18
    )
    
    # Build story (content elements)
    story = []
    
    # Add title page
    _add_title_page(story, analysis_type, title, description)
    
    # Add executive summary
    _add_executive_summary(story, analysis_type, input_params, results)
    
    # Add detailed analysis based on type
    if analysis_type == "unit_economics":
        _add_unit_economics_analysis(story, input_params, results, include_charts)
    elif analysis_type == "pricing_tiers":
        _add_pricing_tiers_analysis(story, input_params, results, include_charts)
    elif analysis_type == "freemium_funnel":
        _add_freemium_funnel_analysis(story, input_params, results, include_charts)
    elif analysis_type == "scenario_analysis":
        _add_scenario_analysis_report(story, input_params, results, include_charts)
    
    # Add appendix
    _add_appendix(story, analysis_type, input_params)
    
    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()


def _get_styles():
    """Get custom paragraph styles"""
    styles = getSampleStyleSheet()
    
    # Custom styles
    styles.add(ParagraphStyle(
        name='CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=30,
        alignment=TA_CENTER,
        textColor=colors.darkblue
    ))
    
    styles.add(ParagraphStyle(
        name='SectionHeading',
        parent=styles['Heading2'],
        fontSize=16,
        spaceAfter=12,
        textColor=colors.darkblue,
        borderWidth=1,
        borderColor=colors.darkblue,
        borderPadding=5
    ))
    
    styles.add(ParagraphStyle(
        name='MetricValue',
        parent=styles['Normal'],
        fontSize=14,
        textColor=colors.darkgreen,
        alignment=TA_CENTER,
        spaceAfter=6
    ))
    
    return styles


def _add_title_page(
    story: List,
    analysis_type: str,
    title: Optional[str],
    description: Optional[str]
):
    """Add title page to PDF report"""
    styles = _get_styles()
    
    # Main title
    main_title = title or f"{analysis_type.replace('_', ' ').title()} Analysis Report"
    story.append(Paragraph(main_title, styles['CustomTitle']))
    story.append(Spacer(1, 0.5*inch))
    
    # UnitSim branding
    story.append(Paragraph("Generated by UnitSim 2.0", styles['Heading3']))
    story.append(Paragraph("Advanced Unit Economics Analysis Platform", styles['Normal']))
    story.append(Spacer(1, 0.3*inch))
    
    # Report metadata
    metadata_data = [
        ['Report Type:', analysis_type.replace('_', ' ').title()],
        ['Generated:', datetime.now().strftime('%B %d, %Y at %I:%M %p')],
        ['Version:', 'UnitSim 2.0'],
        ['Format:', 'Comprehensive Analysis Report']
    ]
    
    metadata_table = Table(metadata_data, colWidths=[2*inch, 3*inch])
    metadata_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.lightgrey)
    ]))
    
    story.append(metadata_table)
    story.append(Spacer(1, 0.5*inch))
    
    # Description if provided
    if description:
        story.append(Paragraph("Report Description", styles['Heading3']))
        story.append(Paragraph(description, styles['Normal']))
        story.append(Spacer(1, 0.3*inch))
    
    # Disclaimer
    disclaimer = """
    <b>Important Notice:</b> This report is generated based on the input parameters provided 
    and uses standard unit economics calculations. Results should be validated against actual 
    business data and used as part of a comprehensive business analysis framework.
    """
    story.append(Paragraph(disclaimer, styles['Normal']))
    
    story.append(PageBreak())


def _add_executive_summary(
    story: List,
    analysis_type: str,
    input_params: Dict[str, Any],
    results: Dict[str, Any]
):
    """Add executive summary section"""
    styles = _get_styles()
    
    story.append(Paragraph("Executive Summary", styles['SectionHeading']))
    story.append(Spacer(1, 0.2*inch))
    
    # Key findings based on analysis type
    if analysis_type == "unit_economics":
        _add_unit_economics_summary(story, results)
    elif analysis_type == "pricing_tiers":
        _add_pricing_tiers_summary(story, results)
    elif analysis_type == "freemium_funnel":
        _add_freemium_funnel_summary(story, results)
    elif analysis_type == "scenario_analysis":
        _add_scenario_analysis_summary(story, results)
    
    story.append(Spacer(1, 0.3*inch))


def _add_unit_economics_summary(story: List, results: Dict[str, Any]):
    """Add unit economics executive summary"""
    styles = _get_styles()
    
    ltv = results.get('ltv', 0)
    ltv_cac_ratio = results.get('ltv_cac_ratio', 0)
    payback_months = results.get('payback_months', 0)
    status = results.get('status', 'Unknown')
    
    # Key metrics table
    summary_data = [
        ['Metric', 'Value', 'Assessment'],
        ['Customer Lifetime Value (LTV)', f'${ltv:,.2f}', ''],
        ['LTV:CAC Ratio', f'{ltv_cac_ratio:.2f}', _assess_ltv_cac(ltv_cac_ratio)],
        ['Payback Period', f'{payback_months:.1f} months', _assess_payback(payback_months)],
        ['Overall Status', status, _get_status_description(status)]
    ]
    
    summary_table = Table(summary_data, colWidths=[2.5*inch, 1.5*inch, 2.5*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    story.append(summary_table)
    
    # Interpretation
    interpretation = f"""
    <b>Key Finding:</b> Your unit economics show a {status.lower()} business model with an LTV:CAC ratio of {ltv_cac_ratio:.2f}. 
    {_get_detailed_interpretation(ltv_cac_ratio, payback_months, status)}
    """
    story.append(Spacer(1, 0.2*inch))
    story.append(Paragraph(interpretation, styles['Normal']))


def _add_pricing_tiers_summary(story: List, results: Dict[str, Any]):
    """Add pricing tiers executive summary"""
    styles = _get_styles()
    
    blended = results.get('blended_metrics', {})
    tiers = results.get('tiers', [])
    
    # Summary metrics
    summary_data = [
        ['Metric', 'Value'],
        ['Total Customers', f"{blended.get('total_customers', 0):,}"],
        ['Total Annual ARR', f"${blended.get('total_annual_arr', 0):,.2f}"],
        ['Blended LTV', f"${blended.get('blended_ltv', 0):,.2f}"],
        ['Blended LTV:CAC', f"{blended.get('blended_ltv_cac_ratio', 0):.2f}"],
        ['Number of Tiers', str(len(tiers))]
    ]
    
    summary_table = Table(summary_data, colWidths=[3*inch, 2*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    story.append(summary_table)


def _add_freemium_funnel_summary(story: List, results: Dict[str, Any]):
    """Add freemium funnel executive summary"""
    styles = _get_styles()
    
    summary = results.get('summary', {})
    stages = results.get('stages', [])
    
    # Key funnel metrics
    summary_data = [
        ['Metric', 'Value'],
        ['Initial Users', f"{summary.get('initial_users', 0):,}"],
        ['Final Converting Users', f"{summary.get('final_users', 0):,}"],
        ['Overall Conversion Rate', f"{summary.get('overall_conversion', 0):.2f}%"],
        ['Total Revenue Potential', f"${summary.get('total_revenue', 0):,.2f}"],
        ['Number of Funnel Stages', str(len(stages))]
    ]
    
    summary_table = Table(summary_data, colWidths=[3*inch, 2*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    story.append(summary_table)


def _add_scenario_analysis_summary(story: List, results: Dict[str, Any]):
    """Add scenario analysis executive summary"""
    styles = _get_styles()
    
    stats = results.get('summary_statistics', {})
    ltv_stats = stats.get('ltv', {})
    simulation = results.get('simulation_summary', {})
    
    # Statistical summary
    summary_data = [
        ['Statistic', 'LTV Value'],
        ['Mean', f"${ltv_stats.get('mean', 0):,.2f}"],
        ['Median', f"${ltv_stats.get('median', 0):,.2f}"],
        ['Standard Deviation', f"${ltv_stats.get('std', 0):,.2f}"],
        ['Minimum', f"${ltv_stats.get('min', 0):,.2f}"],
        ['Maximum', f"${ltv_stats.get('max', 0):,.2f}"],
        ['Iterations Run', f"{simulation.get('n_iterations', 0):,}"]
    ]
    
    summary_table = Table(summary_data, colWidths=[2.5*inch, 2.5*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    story.append(summary_table)


def _add_unit_economics_analysis(
    story: List,
    input_params: Dict[str, Any],
    results: Dict[str, Any],
    include_charts: bool
):
    """Add detailed unit economics analysis"""
    styles = _get_styles()
    
    story.append(Paragraph("Detailed Unit Economics Analysis", styles['SectionHeading']))
    story.append(Spacer(1, 0.2*inch))
    
    # Input parameters table
    story.append(Paragraph("Input Parameters", styles['Heading3']))
    
    input_data = [
        ['Parameter', 'Value', 'Unit'],
        ['Monthly Recurring Revenue', f"${input_params.get('monthlyRecurringRevenue', 0):,.2f}", 'per customer'],
        ['Gross Margin', f"{input_params.get('grossMarginPercent', 0):.1f}%", 'percentage'],
        ['Monthly Churn Rate', f"{input_params.get('monthlyChurnRate', 0):.1f}%", 'percentage'],
        ['Customer Acquisition Cost', f"${input_params.get('customerAcquisitionCost', 0):,.2f}", 'per customer']
    ]
    
    input_table = Table(input_data, colWidths=[3*inch, 1.5*inch, 1.5*inch])
    input_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    story.append(input_table)
    story.append(Spacer(1, 0.3*inch))
    
    # Calculated results
    story.append(Paragraph("Calculated Results", styles['Heading3']))
    
    results_data = [
        ['Metric', 'Value', 'Benchmark'],
        ['Customer Lifetime Value', f"${results.get('ltv', 0):,.2f}", 'Higher is better'],
        ['LTV:CAC Ratio', f"{results.get('ltv_cac_ratio', 0):.2f}", 'Target: 3.0+'],
        ['Payback Period', f"{results.get('payback_months', 0):.1f} months", 'Target: <12 months'],
        ['Business Status', results.get('status', 'Unknown'), _get_status_description(results.get('status', 'Unknown'))]
    ]
    
    results_table = Table(results_data, colWidths=[2.5*inch, 1.5*inch, 2*inch])
    results_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkgreen),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    story.append(results_table)
    story.append(Spacer(1, 0.3*inch))
    
    # Recommendations
    story.append(Paragraph("Recommendations", styles['Heading3']))
    recommendations = _generate_recommendations(results.get('ltv_cac_ratio', 0), results.get('payback_months', 0))
    for rec in recommendations:
        story.append(Paragraph(f"• {rec}", styles['Normal']))
        story.append(Spacer(1, 0.1*inch))


def _add_pricing_tiers_analysis(
    story: List,
    input_params: Dict[str, Any],
    results: Dict[str, Any],
    include_charts: bool
):
    """Add detailed pricing tiers analysis"""
    styles = _get_styles()
    
    story.append(Paragraph("Pricing Tiers Analysis", styles['SectionHeading']))
    story.append(Spacer(1, 0.2*inch))
    
    # Tier performance table
    story.append(Paragraph("Tier Performance Analysis", styles['Heading3']))
    
    tiers = results.get('tiers', [])
    tier_data = [['Tier', 'Price', 'Customers', 'LTV', 'LTV:CAC', 'ARR', 'Status']]
    
    for tier in tiers:
        tier_data.append([
            tier.get('name', ''),
            f"${tier.get('price', 0):,.0f}",
            f"{tier.get('customers', 0):,}",
            f"${tier.get('ltv', 0):,.0f}",
            f"{tier.get('ltv_cac_ratio', 0):.2f}",
            f"${tier.get('annual_arr', 0):,.0f}",
            tier.get('status', '')
        ])
    
    tier_table = Table(tier_data, colWidths=[1*inch, 0.8*inch, 0.8*inch, 0.8*inch, 0.8*inch, 1*inch, 1*inch])
    tier_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    story.append(tier_table)


def _add_freemium_funnel_analysis(
    story: List,
    input_params: Dict[str, Any],
    results: Dict[str, Any],
    include_charts: bool
):
    """Add detailed freemium funnel analysis"""
    styles = _get_styles()
    
    story.append(Paragraph("Freemium Funnel Analysis", styles['SectionHeading']))
    story.append(Spacer(1, 0.2*inch))
    
    # Funnel stages table
    story.append(Paragraph("Funnel Stage Performance", styles['Heading3']))
    
    stages = results.get('stages', [])
    stage_data = [['Stage', 'Name', 'Input Users', 'Output Users', 'Conversion %', 'Drop Off']]
    
    for i, stage in enumerate(stages):
        stage_data.append([
            str(i + 1),
            stage.get('name', f'Stage {i+1}'),
            f"{stage.get('input_users', 0):,}",
            f"{stage.get('output_users', 0):,}",
            f"{stage.get('conversion_rate', 0):.2f}%",
            f"{stage.get('drop_off', 0):,}"
        ])
    
    stage_table = Table(stage_data, colWidths=[0.6*inch, 1.5*inch, 1*inch, 1*inch, 1*inch, 1*inch])
    stage_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    story.append(stage_table)


def _add_scenario_analysis_report(
    story: List,
    input_params: Dict[str, Any],
    results: Dict[str, Any],
    include_charts: bool
):
    """Add detailed scenario analysis report"""
    styles = _get_styles()
    
    story.append(Paragraph("Monte Carlo Scenario Analysis", styles['SectionHeading']))
    story.append(Spacer(1, 0.2*inch))
    
    # Statistical results
    story.append(Paragraph("Statistical Summary", styles['Heading3']))
    
    stats = results.get('summary_statistics', {})
    for metric_name, metric_stats in stats.items():
        if isinstance(metric_stats, dict):
            story.append(Paragraph(f"{metric_name.replace('_', ' ').title()} Statistics:", styles['Heading4']))
            
            stats_data = [['Statistic', 'Value']]
            for stat_name, stat_value in metric_stats.items():
                formatted_value = f"{stat_value:.2f}" if isinstance(stat_value, (int, float)) else str(stat_value)
                stats_data.append([stat_name.title(), formatted_value])
            
            stats_table = Table(stats_data, colWidths=[2*inch, 2*inch])
            stats_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            story.append(stats_table)
            story.append(Spacer(1, 0.2*inch))


def _add_appendix(
    story: List,
    analysis_type: str,
    input_params: Dict[str, Any]
):
    """Add appendix with methodology and definitions"""
    styles = _get_styles()
    
    story.append(PageBreak())
    story.append(Paragraph("Appendix: Methodology & Definitions", styles['SectionHeading']))
    story.append(Spacer(1, 0.2*inch))
    
    # Definitions
    story.append(Paragraph("Key Definitions", styles['Heading3']))
    
    definitions = [
        ("LTV (Lifetime Value)", "Total revenue expected from a customer over their entire relationship with the business."),
        ("CAC (Customer Acquisition Cost)", "Total cost of acquiring a new customer including marketing, sales, and related expenses."),
        ("LTV:CAC Ratio", "Ratio of customer lifetime value to customer acquisition cost. Indicates business efficiency."),
        ("Churn Rate", "Percentage of customers who stop using the service in a given period."),
        ("MRR (Monthly Recurring Revenue)", "Predictable monthly revenue from subscriptions or recurring customers."),
        ("Payback Period", "Time required to recover the customer acquisition cost from the customer's revenue.")
    ]
    
    for term, definition in definitions:
        story.append(Paragraph(f"<b>{term}:</b> {definition}", styles['Normal']))
        story.append(Spacer(1, 0.1*inch))
    
    story.append(Spacer(1, 0.3*inch))
    
    # Methodology
    story.append(Paragraph("Calculation Methodology", styles['Heading3']))
    
    if analysis_type == "unit_economics":
        methodology = """
        <b>Unit Economics Calculations:</b><br/>
        • LTV = (MRR × Gross Margin %) ÷ Monthly Churn Rate<br/>
        • LTV:CAC Ratio = LTV ÷ CAC<br/>
        • Payback Period = CAC ÷ (MRR × Gross Margin %)<br/>
        • Status determined by LTV:CAC ratio benchmarks: Excellent (5+), Great (4-5), Good (3-4), Acceptable (1-3), Poor (<1)
        """
    elif analysis_type == "scenario_analysis":
        methodology = """
        <b>Monte Carlo Simulation Methodology:</b><br/>
        • Random sampling from specified parameter ranges<br/>
        • Multiple iterations to capture uncertainty<br/>
        • Statistical analysis of output distributions<br/>
        • Percentile analysis for risk assessment
        """
    else:
        methodology = f"""
        <b>{analysis_type.replace('_', ' ').title()} Methodology:</b><br/>
        • Standard unit economics principles applied<br/>
        • Industry benchmark comparisons<br/>
        • Comprehensive scenario analysis
        """
    
    story.append(Paragraph(methodology, styles['Normal']))


# Helper functions for assessments and recommendations

def _assess_ltv_cac(ratio: float) -> str:
    """Assess LTV:CAC ratio"""
    if ratio >= 5: return "Excellent"
    elif ratio >= 4: return "Great"
    elif ratio >= 3: return "Good"
    elif ratio >= 1: return "Acceptable"
    else: return "Poor"

def _assess_payback(months: float) -> str:
    """Assess payback period"""
    if months <= 6: return "Excellent"
    elif months <= 12: return "Good"
    elif months <= 18: return "Acceptable"
    else: return "Concerning"

def _get_status_description(status: str) -> str:
    """Get detailed status description"""
    descriptions = {
        "Excellent": "Strong unit economics with high efficiency",
        "Great": "Very good unit economics with solid fundamentals", 
        "Healthy": "Good unit economics with room for optimization",
        "Acceptable": "Adequate unit economics requiring improvement",
        "Poor": "Weak unit economics needing significant changes"
    }
    return descriptions.get(status, "Status assessment unavailable")

def _get_detailed_interpretation(ltv_cac: float, payback: float, status: str) -> str:
    """Get detailed business interpretation"""
    if status == "Excellent":
        return "This indicates a highly efficient business model with strong customer value creation."
    elif status == "Great":
        return "This shows a solid business foundation with good customer economics."
    elif status == "Healthy":
        return "This represents a viable business model with opportunities for optimization."
    elif status == "Acceptable":
        return "This suggests the business is functional but needs improvement in efficiency metrics."
    else:
        return "This indicates challenges in the business model that require attention."

def _generate_recommendations(ltv_cac: float, payback: float) -> List[str]:
    """Generate specific recommendations based on metrics"""
    recommendations = []
    
    if ltv_cac < 3:
        recommendations.append("Focus on improving LTV:CAC ratio by reducing acquisition costs or increasing customer value")
        recommendations.append("Consider optimizing marketing channels for better cost efficiency")
    
    if payback > 12:
        recommendations.append("Work to reduce payback period to under 12 months for better cash flow")
        recommendations.append("Consider strategies to increase early customer revenue or reduce CAC")
    
    if ltv_cac >= 3 and payback <= 12:
        recommendations.append("Maintain current strong unit economics while scaling operations")
        recommendations.append("Consider investing in growth with confidence in your model")
    
    if not recommendations:
        recommendations.append("Continue monitoring unit economics as you scale")
        recommendations.append("Consider A/B testing pricing and acquisition strategies")
    
    return recommendations


# Example usage
if __name__ == "__main__":
    # Test PDF generation
    test_params = {
        "monthlyRecurringRevenue": 100,
        "grossMarginPercent": 80,
        "monthlyChurnRate": 5,
        "customerAcquisitionCost": 500
    }
    
    test_results = {
        "ltv": 1600,
        "ltv_cac_ratio": 3.2,
        "status": "Healthy",
        "payback_months": 6.25
    }
    
    pdf_bytes = generate_pdf_report(
        "unit_economics",
        test_params,
        test_results,
        title="Sample Unit Economics Analysis",
        description="Test report for UnitSim PDF generation"
    )
    
    print(f"Generated PDF report: {len(pdf_bytes)} bytes")
    
    # Could save to file for testing:
    # with open("test_report.pdf", "wb") as f:
    #     f.write(pdf_bytes)